import AppKit
import CryptoKit

/// 读取 / 写入系统剪贴板。会完整复制每一种格式（纯文本、富文本、HTML、图片……），粘贴效果和本机复制一样。
enum Clipboard {
    /// 从另一台电脑写进来的内容带这个标记，避免又被同步回去。
    static let marker = NSPasteboard.PasteboardType("com.gbroseo.portal.remote")
    /// 剪贴板工具约定的「临时 / 自动生成」内容不同步。
    static let skip: Set<String> = [marker.rawValue, "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
    static let maxBytes = 64 << 20

    enum Content {
        case none
        case reps([(Rep, Data)])
        case files([URL])
    }

    static func snapshot() -> Content {
        let pb = NSPasteboard.general
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: skip), let items = pb.pasteboardItems, !items.isEmpty else { return .none }

        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            // UU 远程复制文件时放进剪贴板的占位文件（.uuremote_xxx），不是真文件，不同步
            if urls.contains(where: { $0.lastPathComponent.hasPrefix(".uuremote") }) { return .none }
            return .files(urls)
        }

        var reps: [(Rep, Data)] = []
        for (i, item) in items.enumerated() {
            for t in item.types where !t.rawValue.hasPrefix("com.apple.pasteboard.promised") {
                if let d = item.data(forType: t) { reps.append((Rep(item: i, type: t.rawValue, size: d.count), d)) }
            }
        }
        if reps.reduce(0, { $0 + $1.1.count }) > maxBytes {
            // 太大（比如超大截图带了好几种格式）：只保留文字和 PNG
            reps = reps.filter { $0.0.item == 0 && ($0.0.type == NSPasteboard.PasteboardType.string.rawValue
                                                    || $0.0.type == NSPasteboard.PasteboardType.png.rawValue) }
            if !reps.contains(where: { $0.0.type == NSPasteboard.PasteboardType.png.rawValue }),
               let tiff = pb.data(forType: .tiff), let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
                reps.append((Rep(item: 0, type: NSPasteboard.PasteboardType.png.rawValue, size: png.count), png))
            }
        }
        return reps.isEmpty ? .none : .reps(reps)
    }

    static func apply(_ reps: [(Rep, Data)]) {
        let count = (reps.map(\.0.item).max() ?? 0) + 1
        let items = (0..<count).map { _ in NSPasteboardItem() }
        for (r, d) in reps { items[r.item].setData(d, forType: NSPasteboard.PasteboardType(r.type)) }
        items[0].setData(Data(), forType: marker)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.writeObjects(items)
    }

    static func applyFiles(_ urls: [URL]) {
        let items = urls.map { url -> NSPasteboardItem in
            let it = NSPasteboardItem()
            it.setString(url.absoluteString, forType: .fileURL)
            return it
        }
        items.first?.setData(Data(), forType: marker)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.writeObjects(items)
    }

    /// 内容特征：文字看内容，图片看尺寸（别的软件转存时格式可能变，尺寸不会变）
    static func signature(_ reps: [(Rep, Data)]) -> String? {
        if let s = reps.first(where: { $0.0.type == NSPasteboard.PasteboardType.string.rawValue }),
           let text = String(data: s.1, encoding: .utf8) {
            return "t:" + text.trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let img = reps.first(where: { $0.0.type == NSPasteboard.PasteboardType.png.rawValue || $0.0.type == NSPasteboard.PasteboardType.tiff.rawValue }),
           let rep = NSBitmapImageRep(data: img.1) {
            return "i:\(rep.pixelsWide)x\(rep.pixelsHigh)"
        }
        return nil
    }

    static func signature(_ urls: [URL]) -> String {
        "f:" + urls.map { url -> String in
            let size = (try? FileManager.default.attributesOfItem(atPath: url.path)[.size] as? NSNumber)?.int64Value ?? -1
            return "\(url.lastPathComponent)#\(size)"
        }.sorted().joined(separator: "|")
    }

    static func describe(_ reps: [(Rep, Data)]) -> String {
        let types = Set(reps.map(\.0.type))
        if types.contains(NSPasteboard.PasteboardType.png.rawValue) || types.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            return "图片"
        }
        if let s = reps.first(where: { $0.0.type == NSPasteboard.PasteboardType.string.rawValue }),
           let text = String(data: s.1, encoding: .utf8) {
            let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
            return "文字「\(t.count > 18 ? String(t.prefix(18)) + "…" : t)」"
        }
        return "剪贴板内容"
    }
}


extension Clipboard {
    /// 远程测试用：当前剪贴板的类型、文字摘要和文件名（不传图片内容）
    static func info() -> String {
        let pb = NSPasteboard.general
        let types = (pb.types ?? []).map(\.rawValue)
        var parts = ["types=\(types.filter { !$0.hasPrefix("dyn.") && !$0.contains(" ") })"]
        if let s = pb.string(forType: .string) { parts.append("text=\(s.prefix(60))") }
        if let png = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let digest = SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined().prefix(12)
            parts.append("image=\(png.count)B sha=\(digest)")
        }
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            parts.append("files=\(urls.map(\.lastPathComponent))")
        }
        return parts.joined(separator: " ")
    }

    /// 远程测试用：在本机模拟一次复制（不带传送门标记，所以会被自动同步出去）
    static func simulateCopy(_ kind: String, text: String?, size: Int64) throws -> String {
        let pb = NSPasteboard.general
        switch kind {
        case "image":
            let img = NSImage(size: NSSize(width: 320, height: 180), flipped: false) { r in
                NSColor.systemTeal.setFill(); r.fill()
                ("传送门测试 " + (text ?? "")).draw(at: NSPoint(x: 20, y: 80),
                    withAttributes: [.font: NSFont.boldSystemFont(ofSize: 22), .foregroundColor: NSColor.white])
                return true
            }
            guard let tiff = img.tiffRepresentation, let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
            else { throw PortalError.badFrame }
            pb.clearContents()
            pb.setData(png, forType: .png)
            let digest = SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined().prefix(12)
            return "image=\(png.count)B sha=\(digest)"
        case "file":
            let mb = max(1, min(size, 1024))
            let url = FileManager.default.temporaryDirectory.appendingPathComponent("传送门测试-\(mb)MB.bin")
            FileManager.default.createFile(atPath: url.path, contents: nil)
            let fh = try FileHandle(forWritingTo: url)
            var chunk = Data(count: 1 << 20)
            for i in 0..<Int(mb) {
                chunk.withUnsafeMutableBytes { _ = SecRandomCopyBytes(kSecRandomDefault, 4096, $0.baseAddress!) }
                chunk[0] = UInt8(i & 0xff)
                fh.write(chunk)
            }
            fh.closeFile()
            pb.clearContents()
            pb.writeObjects([url as NSURL])
            return "file=\(url.lastPathComponent)"
        default:
            pb.clearContents()
            pb.setString(text ?? "传送门测试", forType: .string)
            return "text=\(text ?? "")"
        }
    }
}

func formatBytes(_ n: Int64) -> String {
    ByteCountFormatter.string(fromByteCount: n, countStyle: .file)
}
