import AppKit

/// 读取 / 写入系统剪贴板。会完整复制每一种格式（纯文本、富文本、HTML、图片……），粘贴效果和本机复制一样。
enum Clipboard {
    /// 从另一台电脑写进来的内容带这个标记，避免又被同步回去。
    static let marker = NSPasteboard.PasteboardType("com.gbroseo.portal.remote")
    /// 剪贴板工具约定的「临时 / 自动生成」内容不同步。
    static let skip: Set<String> = [marker.rawValue, "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
    static let maxBytes = 64 << 20

    enum Content {
        case none
        case reps([(Rep, Data)])
        case files([URL])
    }

    static func snapshot() -> Content {
        let pb = NSPasteboard.general
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: skip), let items = pb.pasteboardItems, !items.isEmpty else { return .none }

        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }

        var reps: [(Rep, Data)] = []
        for (i, item) in items.enumerated() {
            for t in item.types where !t.rawValue.hasPrefix("com.apple.pasteboard.promised") {
                if let d = item.data(forType: t) { reps.append((Rep(item: i, type: t.rawValue, size: d.count), d)) }
            }
        }
        if reps.reduce(0, { $0 + $1.1.count }) > maxBytes {
            // 太大（比如超大截图带了好几种格式）：只保留文字和 PNG
            reps = reps.filter { $0.0.item == 0 && ($0.0.type == NSPasteboard.PasteboardType.string.rawValue
                                                    || $0.0.type == NSPasteboard.PasteboardType.png.rawValue) }
            if !reps.contains(where: { $0.0.type == NSPasteboard.PasteboardType.png.rawValue }),
               let tiff = pb.data(forType: .tiff), let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
                reps.append((Rep(item: 0, type: NSPasteboard.PasteboardType.png.rawValue, size: png.count), png))
            }
        }
        return reps.isEmpty ? .none : .reps(reps)
    }

    static func apply(_ reps: [(Rep, Data)]) {
        let count = (reps.map(\.0.item).max() ?? 0) + 1
        let items = (0..<count).map { _ in NSPasteboardItem() }
        for (r, d) in reps { items[r.item].setData(d, forType: NSPasteboard.PasteboardType(r.type)) }
        items[0].setData(Data(), forType: marker)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.writeObjects(items)
    }

    static func applyFiles(_ urls: [URL]) {
        let items = urls.map { url -> NSPasteboardItem in
            let it = NSPasteboardItem()
            it.setString(url.absoluteString, forType: .fileURL)
            return it
        }
        items.first?.setData(Data(), forType: marker)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.writeObjects(items)
    }

    static func describe(_ reps: [(Rep, Data)]) -> String {
        let types = Set(reps.map(\.0.type))
        if types.contains(NSPasteboard.PasteboardType.png.rawValue) || types.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            return "图片"
        }
        if let s = reps.first(where: { $0.0.type == NSPasteboard.PasteboardType.string.rawValue }),
           let text = String(data: s.1, encoding: .utf8) {
            let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
            return "文字「\(t.count > 18 ? String(t.prefix(18)) + "…" : t)」"
        }
        return "剪贴板内容"
    }
}

func formatBytes(_ n: Int64) -> String {
    ByteCountFormatter.string(fromByteCount: n, countStyle: .file)
}
